species: Human

seq_info:
  type: ChIP-Seq
  mode: PE
  replicate: 2

path: /home/xfu/Project/20200421_YJiang/ChIP-Seq/fastq

samples:
  - Input
  - IP.1
  - IP.2

treat:
  - IP.1
  - IP.2

control:
  - Input
  - Input

cpu: 30

Rscript_path: /home/xfu/R/3.5.1/bin/Rscript

conda_path: /home/xfu/miniconda3/envs/gmatic/bin

adapter: /home/xfu/miniconda3/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

#p: 1e-5
p: 1e-2

index: /home/xfu/Gmatic6/genome/hg38/hg38
 
chromSize: /home/xfu/Gmatic6/genome/hg38/hg38.chrom.sizes
 
fasta: /home/xfu/Gmatic6/genome/hg38/hg38.fa
 
txdb: /home/xfu/Gmatic7/gene/human/txdb/GRCh38_v29_txdb.sqlite
 
gene_anno: /home/xfu/Gmatic7/gene/human/GRCh38_v29_id2name2biotype
 
gene_bed: /home/xfu/Gmatic7/gene/human/GRCh38_v29_gene.bed
 
IGV: /home/xfu/igv/genomes/hg38.genome
 
gsize: hs
