configfile: "config.yaml"

rule all:
	input:
		expand('clean/{sample}_R1_paired.fastq.gz', sample=config['samples']),
		expand('clean/{sample}_R2_paired.fastq.gz', sample=config['samples']),
		expand('fastqc/raw/{sample}_R1_fastqc.html', sample=config['samples']),
		expand('fastqc/raw/{sample}_R2_fastqc.html', sample=config['samples']),
		expand('fastqc/clean/{sample}_R1_paired_fastqc.html', sample=config['samples']),
		expand('fastqc/clean/{sample}_R2_paired_fastqc.html', sample=config['samples']),
		expand('stat/fastqc_stat.tsv'),
		expand('bam/{sample}.bam', sample=config['samples']),
		expand('bam/{sample}.bam.bai', sample=config['samples']),
		expand('bam/{sample}.bamqc', sample=config['samples']),
		expand('stat/bamqc_stat.tsv'),
		expand('track/{sample}.tdf', sample=config['samples']),
		['peak_{p}/{treat}_c_{control}_peaks.bed'.format(treat=x[0], control=x[1], p=config['p']) for x in zip(config['treat'], config['control'])],
		['peak_{p}/{treat}_c_{control}_peaks.xls'.format(treat=x[0], control=x[1], p=config['p']) for x in zip(config['treat'], config['control'])],
		['peak_{p}/{treat}_c_{control}_peaks_anno.xls'.format(treat=x[0], control=x[1], p=config['p']) for x in zip(config['treat'], config['control'])],
		['peak_{p}/{treat}_c_{control}_peaks_annoPie.pdf'.format(treat=x[0], control=x[1], p=config['p']) for x in zip(config['treat'], config['control'])],

rule fastqc_raw_PE:
	input:
		config['path']+'/{sample}_R1.fastq.gz',
		config['path']+'/{sample}_R2.fastq.gz'
	output:
		'fastqc/raw/{sample}_R1_fastqc.html',
		'fastqc/raw/{sample}_R2_fastqc.html'
	params:
		conda = config['conda_path']
	shell:
		'{params.conda}/fastqc -t 2 -o fastqc/raw {input}'

rule trimmomatic_PE:
	input:
		r1 = config['path']+'/{sample}_R1.fastq.gz',
		r2 = config['path']+'/{sample}_R2.fastq.gz'
	output:
		r1_paired = 'clean/{sample}_R1_paired.fastq.gz',
		r2_paired = 'clean/{sample}_R2_paired.fastq.gz',
		r1_unpaired = 'clean/{sample}_R1_unpaired.fastq.gz',
		r2_unpaired = 'clean/{sample}_R2_unpaired.fastq.gz'
	params:
		adapter = config['adapter'],
		conda = config['conda_path']
	shell:
		'{params.conda}/trimmomatic PE -threads 3 -phred33 {input.r1} {input.r2} {output.r1_paired} {output.r1_unpaired} {output.r2_paired} {output.r2_unpaired} ILLUMINACLIP:{params.adapter}:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36'

rule fastqc_clean_PE:
	input:
		'clean/{sample}_R1_paired.fastq.gz',
		'clean/{sample}_R2_paired.fastq.gz'
	output:
		'fastqc/clean/{sample}_R1_paired_fastqc.html',
		'fastqc/clean/{sample}_R2_paired_fastqc.html'
	params:
		conda = config['conda_path']
	shell:
		'{params.conda}/fastqc -t 2 -o fastqc/clean {input}'

rule fastqc_stat_PE:
	input:
		['fastqc/raw/{sample}_R1_fastqc.html'.format(sample=x) for x in config['samples']],
		['fastqc/raw/{sample}_R2_fastqc.html'.format(sample=x) for x in config['samples']],
		['fastqc/clean/{sample}_R1_paired_fastqc.html'.format(sample=x) for x in config['samples']],
		['fastqc/clean/{sample}_R2_paired_fastqc.html'.format(sample=x) for x in config['samples']]
	output:
		'stat/fastqc_stat.tsv'
	params:
		Rscript = config['Rscript_path']
	shell:
		'{params.Rscript} script/reads_stat_by_fastqcr.R'

rule bowtie2:
	input:
		r1 = 'clean/{sample}_R1_paired.fastq.gz',
		r2 = 'clean/{sample}_R2_paired.fastq.gz'
	output:
		bam = 'bam/{sample}.bam'
	params:
		prefix = 'bam/{sample}',
		cpu = config['cpu'],
		index = config['index'],
		conda = config['conda_path']		
	shell:
		"{params.conda}/bowtie2 -p {params.cpu} -x {params.index} -1 {input.r1} -2 {input.r2}|{params.conda}/samtools view -Sh -q 30 -F 4 -|grep -v 'XS:'|{params.conda}/samtools view -Shub|{params.conda}/samtools sort - -T {params.prefix} -o {output.bam}"

rule bam_idx:
	input:
		bam = 'bam/{sample}.bam'
	output:
		bai = 'bam/{sample}.bam.bai'
	params:
		conda = config['conda_path']
	shell:
		'{params.conda}/samtools index {input.bam} {output.bai}'

rule bam_qc:
	input:
		bam = 'bam/{sample}.bam'
	output:
		bamqc_dir = 'bam/{sample}.bamqc',
		#bamqc_html = 'bam/{sample}.bamqc/qualimapReport.html'
	params:
		cpu = config['cpu'],
		conda = config['conda_path']
	shell:
		"{params.conda}/qualimap bamqc --java-mem-size=10G -nt {params.cpu} -bam {input.bam} -outdir {output.bamqc_dir}"

rule bam_qc_stat:
	input:
		['bam/{sample}.bamqc/qualimapReport.html'.format(sample=x) for x in config['samples']],
		'stat/fastqc_stat.tsv'
	output:
		'stat/bamqc_stat.tsv'
	params:
		Rscript = config['Rscript_path']		
	shell:
		"{params.Rscript} script/mapping_stat_by_bamqc.R"

rule bam2bed:
	input:
		bam = 'bam/{sample}.bam'
	output:
		bed = 'MAnorm/{sample}.bed'
	shell:
		"bedtools bamtobed -split -i {input.bam} > {output.bed}"

rule bam2count:
	input:
		bam = 'bam/{sample}.bam'
	output:
		cnt = 'bam/{sample}.cnt'
	params:
		conda = config['conda_path']
	shell:
		"{params.conda}/samtools view -c -F 4 {input.bam} > {output.cnt}"
		
rule bam2bedgraph:
	input:
		bam = 'bam/{sample}.bam',
		cnt = 'bam/{sample}.cnt'
	output:
		bg = 'track/{sample}.bedgraph'
	params:
		conda = config['conda_path']
	shell:
		"X=`awk '{{print 1/$1*1000000}}' {input.cnt}`; "
		"{params.conda}/bedtools genomecov -ibam {input.bam} -bga -scale $X -split > {output.bg}"

rule bedgraph2tdf:
	input:
		bg = 'track/{sample}.bedgraph'
	output:
		tdf = 'track/{sample}.tdf'
	params:
		IGV = config['IGV'],
		conda = config['conda_path']
	shell:
		"{params.conda}/igvtools toTDF {input.bg} {output.tdf} {params.IGV}"

rule macs14:
	input:
		treat = 'bam/{treat}.bam',
		control = 'bam/{control}.bam'
	output:
		bed = 'peak_{p}/{treat}_c_{control}_peaks.bed',
		xls = 'peak_{p}/{treat}_c_{control}_peaks.xls'
	params:
		gsize = config['gsize'],
		pvalue = config['p'],
		prefix = 'peak_{p}/{treat}_c_{control}'
	shell:
		'macs14 -t {input.treat} -c {input.control} -g {params.gsize} -p {params.pvalue} -n {params.prefix} --nomodel'

rule peak_anno:
	input:
		bed = 'peak_{p}/{treat}_c_{control}_peaks.bed'
	output:
		xls = 'peak_{p}/{treat}_c_{control}_peaks_anno.xls',
		pie = 'peak_{p}/{treat}_c_{control}_peaks_annoPie.pdf'
	params:
		txdb = config['txdb'],
		gene_anno = config['gene_anno'],
		Rscript = config['Rscript_path']
	shell:
		"{params.Rscript} script/peak_anno.R {input} {params.txdb} {params.gene_anno} {output}"	

